version: "3.9"
services:
        servidor-web:
                build:
                        context: .
                        dockerfile: dockerfile
                ports: 
                  - "8080:8080"
