apiVersion: apps/v1
kind: Deployment
metadata:
        name: mi-deployment
spec:
        replicas: 1
        selector:
                matchLabels:
                        component: servidor-web
        template:
                metadata:
                        labels:
                                component: servidor-web
                 spec:
                         volumes:
                                 - name: mi-vp
                                   persistentVolumeClaim:
                                           claimName: mi-reclamacion-vp
                         containers:
                                 - name: mi-pod
                                   image: iria2000/jetty-iria:v2
                                   ports:
                                           - containerPort: 8080
                                   volumeMounts:
                                           - name: mi-vp
                                             mountPath: /var/lib/jetty/resources
