apiVersion: apps/v1
kind: Deployment
metadata:
        name: mi-deployment
spec:
        replicas: 1
        selector:
          matchLabels:
            component: servidor-web
        template:
          metadata:
            labels:
              component: servidor-web
          spec:
            containers:
            - name: mi-pod
              image: iria2000/jetty-iria:v1
              ports:
              - containerPort: 8080
